-- MySQL Script generated by MySQL Workbench
-- Sat Dec  5 18:19:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Distributor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Distributor` (
  `DistributorID` INT NOT NULL,
  `DistributorName` VARCHAR(100) NULL,
  PRIMARY KEY (`DistributorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CustomerID` INT NOT NULL,
  `CustomerLastName` VARCHAR(50) NOT NULL,
  `CustomerFirstName` VARCHAR(50) NOT NULL,
  `CustomerEmail` VARCHAR(50) NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Store` (
  `StoreID` INT NOT NULL,
  `StoreName` VARCHAR(100) NOT NULL,
  `StoreLocation` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`StoreID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `BrandID` INT NOT NULL,
  `BrandName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`BrandID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shipment` (
  `ShipmentID` INT NOT NULL,
  `DistributorID` INT NOT NULL,
  `StoreID` INT NOT NULL,
  PRIMARY KEY (`ShipmentID`),
  INDEX `DistributorID_idx` (`DistributorID` ASC),
  INDEX `StoreID_idx` (`StoreID` ASC),
  CONSTRAINT `DistributorID`
    FOREIGN KEY (`DistributorID`)
    REFERENCES `mydb`.`Distributor` (`DistributorID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `StoreID`
    FOREIGN KEY (`StoreID`)
    REFERENCES `mydb`.`Store` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `ItemID` INT NOT NULL,
  `BrandID` INT NULL,
  `ItemName` VARCHAR(100) NULL,
  PRIMARY KEY (`ItemID`),
  INDEX `BrandIT_idx` (`BrandID` ASC),
  CONSTRAINT `BrandID`
    FOREIGN KEY (`BrandID`)
    REFERENCES `mydb`.`Brand` (`BrandID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustPhoneNum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CustPhoneNum` (
  `CustomerPhoneNumber` INT NOT NULL,
  `CustID` INT NULL,
  PRIMARY KEY (`CustomerPhoneNumber`),
  INDEX `CustID_idx` (`CustID` ASC),
  CONSTRAINT `CustID`
    FOREIGN KEY (`CustID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Buys` (
  `CustID` INT NOT NULL,
  `ItemID` INT NOT NULL,
  `Count` INT NOT NULL,
  PRIMARY KEY (`CustID`),
  INDEX `ItemID_idx` (`ItemID` ASC),
  CONSTRAINT `buys_CustID`
    FOREIGN KEY (`CustID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `buys_ItemID`
    FOREIGN KEY (`ItemID`)
    REFERENCES `mydb`.`Item` (`ItemID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stocks` (
  `StoreID` INT NOT NULL,
  `ItemID` INT NOT NULL,
  `Count` INT NOT NULL,
  PRIMARY KEY (`StoreID`),
  INDEX `ItemID_idx` (`ItemID` ASC),
  CONSTRAINT `stocks_ItemID`
    FOREIGN KEY (`ItemID`)
    REFERENCES `mydb`.`Item` (`ItemID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `stocks_StoreID`
    FOREIGN KEY (`StoreID`)
    REFERENCES `mydb`.`Store` (`StoreID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contains` (
  `ItemID` INT NOT NULL,
  `ShipmentID` INT NOT NULL,
  `Count` INT NOT NULL,
  PRIMARY KEY (`ShipmentID`),
  INDEX `ShipmentID_idx` (`ShipmentID` ASC),
  CONSTRAINT `contains_ItemID`
    FOREIGN KEY (`ItemID`)
    REFERENCES `mydb`.`Item` (`ItemID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `contains_ShipmentID`
    FOREIGN KEY (`ShipmentID`)
    REFERENCES `mydb`.`Shipment` (`ShipmentID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
